repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: double-quote-string-fixer
    -   id: debug-statements
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
-   repo: local
    hooks:
    -   id: pytest-check
        name: PyTest Runner
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
